%% Приставки СИ
\newcommand{\sda}{\text{да}}
\renewcommand{\sh}{\text{г}}
\newcommand{\sk}{\text{к}}
\newcommand{\sM}{\text{М}}
\newcommand{\sG}{\text{Г}}
\newcommand{\sT}{\text{Т}}
\newcommand{\sP}{\text{П}}
\newcommand{\sE}{\text{Э}}
\newcommand{\sZ}{\text{З}}
\newcommand{\sY}{\text{И}}
\newcommand{\sd}{\text{д}}
\renewcommand{\sc}{\text{с}}
\newcommand{\sm}{\text{м}}
\newcommand{\smu}{\text{мк}}
\newcommand{\sn}{\text{н}}
\renewcommand{\sp}{\text{п}}
\renewcommand{\sf}{\text{ф}}
\newcommand{\sa}{\text{а}}
\newcommand{\sz}{\text{з}}
\newcommand{\sy}{\text{и}}

%% Базовые единицы СИ
\newcommand{\m}{\text{м}}
\newcommand{\kg}{\text{кг}}
\newcommand{\s}{\text{с}}
\newcommand{\A}{\text{А}}
\newcommand{\K}{\text{К}}
\newcommand{\mol}{\text{моль}}
\newcommand{\kd}{\text{кд}}

%% Некоторые производные единицы
% Механика
\newcommand{\cm}{\text{см}}
\newcommand{\mm}{\text{мм}}
\newcommand{\km}{\text{км}}
\newcommand{\g}{\text{г}}
\newcommand{\N}{\text{Н}}
\newcommand{\J}{\text{Дж}}
\newcommand{\erg}{\text{эрг}}

% Электромагнетизм
\newcommand{\V}{\text{В}}
\newcommand{\T}{\text{Тл}}
\renewcommand{\G}{\text{Гс}}
\newcommand{\Wb}{\text{Вб}}
\newcommand{\Oe}{\text{Э}}
\newcommand{\Ohm}{\text{Ом}}
\newcommand{\F}{\text{Ф}}
\renewcommand{\H}{\text{Гн}}
